# Generated by Django 5.2.6 on 2025-09-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='start_date',
            new_name='week_start',
        ),
    ]
